### ISSUE TITLE
Create documentation for GCE provider in cluster-autoscaler

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/autoscaler#5730]
### Problem
GKE deploys cluster-autoscaler for you and that's probably sufficient for most of the cases but if you want to deploy a custom cluster-autoscaler in your Kubernetes cluster hosted on GCP, there is [no documentation available](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/gce) around how to configure your own cluster-autoscaler using GCE provider.

Having documentation like other cloud providers might be helpful for users. 
Example:
* AWS: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws
* Cluster API: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi
* Azure: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/azure 

I usually link [my own blogpost](https://vadasambar.com/post/kubernetes/how-to-deploy-custom-ca-on-gcp/) for how to deploy and to some extent configure your own custom cluster-autoscaler on GKE but I don't think it's a good idea to rely on a third party website since it might just go away in the future. 

### Related
- https://github.com/kubernetes/autoscaler/issues/966
- https://kubernetes.slack.com/archives/C09R1LV8S/p1682500801224359

### TODO
- [ ] decide the scope of the documentation
- [ ] create a PR and get it reviewed
- [ ] if it seems like a good idea to cover some topics in another issue/PR, create an issue and link to this issue

**Comment by js-max** [comment]
Any news around this?

**Comment by larssb** [comment]
Yeah getting this would be nice!

**Comment by js-max** [comment]
Any news around this?

**Comment by evolv34** [comment]
@js-max Hope this 
[article](https://prashanth-cvvp.medium.com/kubernetes-autoscaler-deployment-gcp-66e59f499377) is helpful. please check the required configuration on the instance template and cluster-autoscaler at the end of the article.
