### ISSUE TITLE
Improve the VPA's local dev and test scripts

### ISSUE THREAD

**Issue by adrianmoisey** [kubernetes/autoscaler#7455]
The VPA's scripts for running e2e tests locally are out dated and don't work on modern Apple Silicon Macs.

There are also some quality of life improvements that could be done to make testing and local dev easier and neater, for example this [15 minute sleep](https://github.com/kubernetes/autoscaler/blob/d06fe04ccd1814ce5ab8c4945432806a9e269bcd/vertical-pod-autoscaler/e2e/v1/recommender.go#L143) could be improved on.

I plan to start tidying this area of the VPA up, making it easier and better to run tests.

/area vertical-pod-autoscaler
/assign 

Some ideas:
1. Make e2e tests run locally ✅ 
2. Speed up e2e tests (some sleeps don't make much sense to keep) ✅
3. Remove unnecessary logs (lots of warnings are outputted)
4. Improve documentation on running tests
5. Improve scripts (how much reusability can we get between local and non-local e2e scripts?)
6. Bump metrics-server

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes/autoscaler/pull/7457
- [ ] https://github.com/kubernetes/autoscaler/pull/7456
- [ ] https://github.com/kubernetes/autoscaler/pull/7483
- [ ] https://github.com/kubernetes/autoscaler/pull/7488
- [ ] https://github.com/kubernetes/autoscaler/pull/7506
- [ ] https://github.com/kubernetes/autoscaler/pull/7505
```

**Comment by adrianmoisey** [comment]
/triage accepted

Making progress, but not going to call this done just yet
